repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ["-i", "--global-config=pep8.cfg",]
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test
        args: ['--django']
    -   id: requirements-txt-fixer
    -   id: flake8
        args: ["--config=flake8.cfg"]
        exclude: migrations
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.2.0
    hooks:
    -   id: pyupgrade
