# Config file for automatic testing at travis-ci.org
sudo: required

services:
  - docker

# command to run tests using coverage, e.g. python setup.py test
script:
  docker build -t django-changelog .
after_success:
  - codecov -e TOX_ENV
